### ISSUE TITLE
Using OpenBox instead of xfwm4

### ISSUE THREAD

**Issue by darealshinji** [thor27/steam-login#28]
I personally prefer OpenBox as a lightweight window manager. It doesn't need much ressources (though it's probably not much difference to xfwm4), it has less dependencies and if you're stuck inside the window manager, you can quit from the context menu.

https://github.com/darealshinji/steam-login/blob/openbox/steam-login/steam-de#L83

**Comment by darealshinji** [comment]
I've re-uploaded the OpenBox version: https://github.com/darealshinji/steam-session-openbox/

**Comment by Garoe** [comment]
Would it be possible to make OpenBox version the default one?

**Comment by Nefelim4ag** [comment]
About openbox support: https://github.com/thor27/steam-login/pull/37

**Comment by thor27** [comment]
Master version now supports openbox if available.
