### ISSUE TITLE
Ctrl+Space changes keyboard layout

### ISSUE THREAD

**Issue by wleoncio** [thor27/steam-login#33]
While in game, Ctrl+Space makes a keyboard layout selection dialog appear, capturing control from the game. I imagine this is due to my main DE (Unity) having several languages installed.

I've tried minimizing Big Picture under xfwm4 and access a keyboard-layout window to no success.

How can I prevent this window from showing?

**Comment by thor27** [comment]
On your /usr/bin/steam-de script, remove the line "gnome-settings-daemon &" that should prevent this.
