### ISSUE TITLE
Use wait instead of busy loop?

### ISSUE THREAD

**Issue by kakra** [thor27/steam-login#38]
https://github.com/thor27/steam-login/blob/22d4a2d573a998f16f42376fcf7795d09784a5d2/steam-login/usr/bin/steam-de#L278

Wouldn't it make more sense to use "wait $STEAM_PID"?

**Comment by thor27** [comment]
yes, you are right.

**Comment by thor27** [comment]
Tried it and it didn't work because steampid is not shild of that interpreter. If you manage to make it work, please send a PR. Thanks!
